### ISSUE TITLE
Add Multi-SimLex

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1010]
Okay, my suggestion is to close this PR now, and to look instead at the new list, with all similarities, which I extracted from the simlex project. 

I attach the code I used here:

[multisimlex.zip](https://github.com/concepticon/concepticon-data/files/5591569/multisimlex.zip)

I follow a very simple principle: if for the multiple occurrence of a given concept across all langauges, we only observe the same translation in all cases, we judge these as synonyms and give them the same number. If we encounter even only one language with a different word form, we assume that this should be kept separately. 

Based on this assumption, I then linked automatically, using the pysen library, but only with one suggestion. 

The scores are now listed in the network form we tend to use. First, we have a reference to similex, by providing an ID consisting of the simlex ID and the position of the word (0 or 1), then we have all scores for multiple occurrences represented by space-separated strings as floats. 

All in all, this is a straightforward way which can also be used to generate a network now. 

Since the data gives many key glosses in different languages, it is furthermore important to add them manually. 

In cases of synonyms in English, which are expressed by different words in other languages I'd ask annotators to consult the word that actually differs (which is easy to find, I think), and ideally check if this semantic difference really WARRANTS to be mapped to a different concept in concepticon. 

I have updated the sheet with the new data, and ask all contributors to use the sheet to correct mappings (you can add a new column "COMMENT" where you put your name or other things in case of doubt), and to make use of conditional formatting, which I have NOT added yet. 

I'll make a final check, once these mappings are done. 

We can either transfer this discussion to another issue, OR we do it here. I am fine with both.

_Originally posted by @LinguList in https://github.com/concepticon/concepticon-data/issues/1007#issuecomment-733123163_

**Comment by AnnikaTjuka** [comment]
The updated Google Sheet can be found [here](https://docs.google.com/spreadsheets/d/1jfpwsqtQXQqkKyZh4fGWfm-9fx30y2lgO8HfMJ2uz_c/edit?usp=sharing).

**Comment by AnnikaTjuka** [comment]
Next steps: 

1. I'll add the conditional formatting to the sheet.
2. I'll check the mappings and let the reviewers (@tresoldi, @Schweikhard, @MacyL) know when I'm finished so that you can add your comments.

As soon as we have the final list, I'll create a new PR.

**Comment by AnnikaTjuka** [comment]
Ok, so I corrected the mappings to the best of my ability. Note that I don't speak any of the languages in the list (except for English), so feel free to correct my choices if you know the correct meaning behind the words. Other things to keep in mind:

- The conditional formatting seems to have difficulties with the different writing systems. At least in Arabic, I found a few cases where the duplicates weren't recognized.
- If there are multiple possible mappings, I followed the existing mappings in Concepticon for Russian and Chinese (if applicable). 
- In most double-mapping cases there is at least one language that varied in its differentiation from the other languages. So often there are still only 1-2 mappings to the same concept (except for some concrete objects, e.g, _honey_ and _gun_).
- I'm not sure why, but Kiswahili seems to differentiate almost all words. Maybe the translations were mixed up, but after checking the script provided by @LinguList, I couldn't find a mistake on our end. 

I'd suggest that you delete/add mappings in the columns CONCEPTICON_ID/GLOSS directly. I also added three columns "Comment Tiago/Nathanael/Mei-Shin" where you can discuss peculiar cases. 

Looking forward to your reviews @tresoldi, @Schweikhard, and @MacyL.

**Comment by AnnikaTjuka** [comment]
PS: I named the current version of the Google Sheet "Revised Annika". It might be useful if you also name the version of the file after you finished your review.

**Comment by LinguList** [comment]
Nice, I'll make a final check of the data, once everybody looked at it!

**Comment by LinguList** [comment]
@AnnikaTjuka, please write an email to me, to remind me, in case I forget this.

**Comment by AnnikaTjuka** [comment]
> @AnnikaTjuka, please write an email to me, to remind me, in case I forget this.

Sure, will do!

**Comment by Schweikhard** [comment]
I took a look at the Kiswahili words, and I have the impression that in several cases they do not translate the concept, but the other concept of the pair. Look e.g. at the translations for ball -  raketi (racket, according to GT) does not refer to any ball but is a translation of the other word of the word pair, racket.

**Comment by AnnikaTjuka** [comment]
> I'm not sure why, but Kiswahili seems to differentiate almost all words. Maybe the translations were mixed up, but after checking the script provided by @LinguList, I couldn't find a mistake on our end.

Yes, that was my impression as well. See my comment above.

**Comment by Schweikhard** [comment]
Why did you often only map one of the concepts? E.g. why only the aunt related to nephew and not the one related to uncle?

**Comment by Schweikhard** [comment]
> Yes, that was my impression as well. See my comment above.

Okay, then the mistake is in the original data. So we probably best just ignore that column.

**Comment by AnnikaTjuka** [comment]
See my comment above:

> In most double-mapping cases there is at least one language that varied in its differentiation from the other languages. So often there are still only 1-2 mappings to the same concept (except for some concrete objects, e.g, honey and gun).

In the case of _aunt_, Cantonese seems to differentiate between the two translations for the English word _aunt_.

**Comment by Schweikhard** [comment]
Hm yes, but Estonian differentiates between 2 of the 3 cases of _accuse_ and you still mapped both to ACCUSE. That's what I'm having trouble understanding.

**Comment by AnnikaTjuka** [comment]
Ah, I didn't catch that because it was not highlighted by the conditional formatting.

It is a very long list, so there are probably various mistakes. Feel free to correct my mappings if you find it necessary (especially to keep it consistent).

**Comment by AnnikaTjuka** [comment]
If you name the version after your review, we can easily compare my and your mappings.

**Comment by Schweikhard** [comment]
So the guideline is, only things should receive the same mapping when we know for sure that the meaning any language makes is irrelevant in regards to the meaning of the concept in Concepticon. If we don't know for sure, we only map the first case, or the case that based on what we know seems to fit best.

Okay, then I'll work on a copy of the file and give the link once I'm done.

**Comment by Schweikhard** [comment]
Oh, and as part of the guideline: We ignore the Kiswahili column as it's obviously unreliable.

**Comment by AnnikaTjuka** [comment]
@Schweikhard Please **do not** work with a copy! You can name the version of the file.

**Comment by Schweikhard** [comment]
Ah, got it, didn't know about the make a version feature.

**Comment by Schweikhard** [comment]
By "removed duplicate" in my notes I mean, removed cases where things with different translations had the same mapping.

**Comment by AnnikaTjuka** [comment]
Regarding the guidelines: Sounds good. But please keep in mind, that we sometimes have different glosses of the same language mapped to one concept in Concepticon. For lack of a better example, I can only think of Russian, where we have currently лошадь and конь mapped to HORSE.

**Comment by Schweikhard** [comment]
Yes - for these cases, we'd need a speaker of the language in question to tell us whether it really refers to the same thing (or close enough to the same thing).

For now, I'll just remove these duplicates, unless I spot cases where I see that the douple mapping should be kept. (and there I'll also leave a note)
Deciding which of several duplicates to map is a later step I guess, so I'll just keep the first one when unmapping.

**Comment by Schweikhard** [comment]
I went through the first 100 rows for now.
If we really want to ignore the Kiswahili, it might make sense to rather run the script again with adjustment for that, instead of fixing it all manually.

**Comment by AnnikaTjuka** [comment]
I wouldn't fix it manually either. We might just delete the Kiswahili column (if the error is in the original data).

**Comment by LinguList** [comment]
@AnnikaTjuka and @Schweikhard. For the discussion about multi-mappings: I support them with SimLex, since what is crucial is the way the data was produced. It is much less of a concepticon-approach, but rather starts from English, without paying much attention to the concepts/meaning behind the words in a given pair. Then they give the pairs to translators, who are supposed to translate them into the target language, but they are not allowed to use the same word where English uses different ones (!). So English has for example "car vs. horse" and "automobile vs. airplane", and the translater MUST use two different words in Spanish as well.

This means, in my interpretation:

1. the translation is guided by some conceptual thinking (*lie* in "lie vs. bed" would be mapped to "lie down", but in "lie" vs. "cheat" it would be mapped to "lie (mislead)"), this justifies mapping to concepticon
2. the data is not "purest" in the term of being really interested in the BEST translation, but also bound by principles that would not really make sense in my opinion (but they may have ideas in their paper)
3. the translation is not guided by means differently than the pairs and the restriction that one can translate differently what is the same in English, but not the same what is different in English

Now, what I made was: seek if something is distinguished or not. It is possible that translations use synonyms, so it does NOT make sense to not multi-map here (e.g., "uncle vs. child" and "uncle vs. aunt", I doubt there is a concept difference here). But, in some cases, we can indeed find that English words have many different meanings, and the distinction in different languages helps here.

**Comment by LinguList** [comment]
So I would argue: what receives the same mapping depends on your judgments.

**Comment by LinguList** [comment]
And for Kiswahili: can you please check the original data? @AnnikaTjuka, you have a good understanding of the original file structure, right? Maybe they swapped their data...

**Comment by AnnikaTjuka** [comment]
> And for Kiswahili: can you please check the original data? @AnnikaTjuka, you have a good understanding of the original file structure, right? Maybe they swapped their data...

Yes, sure. I'll have a look at the original data for Kiswahili until tomorrow.

**Comment by AnnikaTjuka** [comment]
So I took a closer look at the Kiswahili data and I'd like to vote to delete the column. 

Here is why: I did not find that the translation columns were swapped. I couldn't make out a clear pattern that would allow us to find the right translation (additionally we don't have a native speaker whom we could ask). In the following, I list some examples, which are understandable for non-native speakers:

Correct:
SWA 1 | SWA 2 | translation 1 | translation 2
-- | -- | -- | --
CD | kompyuta | disc | computer
gari | teksi | car | cab
mama | mke | mother | wife
burudani | mpira wa miguu | fun | football

False:
SWA 1 | SWA 2 | translation 1 | translation 2
-- | -- | -- | --
skiing | ubao wa theluji | snowboard | skiing
glasi | baji | badge | glass
shower | monasteri | monastery | shower
soka | mpira wa miguu | football | soccer

**Comment by AnnikaTjuka** [comment]
> Looking at simlex again (our google sheet), I think now we should exclude Kiswahili and run it again, since this will further reduce the number of concepts.

_Originally posted by @LinguList in_ https://github.com/concepticon/concepticon-data/pull/1019#issuecomment-756166180

**Comment by LinguList** [comment]
So I re-run the code now, exclude Kiswahili, and then update the google sheet (or add the data to a new sheet). We were also missing the IDs for the word pairs themselves, which is not that nice...

**Comment by LinguList** [comment]
I have one more suggestion, since this is otherwise getting far too complex for us: I removed now in the spreadsheet SimLexSmall all languages but Russian, Chinese, Spanish, and French, so we have those languages where our team understands the semantics. In these cases, one needs to check the mapping and see if the double-mappings are trivial or not. E.g., French translation for wife is "femme" and "épouse", obviously direct synonyms, so no need to treat differently, and we should put them into the same cell, where we can write "femme (femme, épouse)" to reflect multiple entries. 

But so far, all that needs to be done is to CONFIRM concepticcon mappings and use them on multiple entries with the same concepticon ID where one thinks the entries BELONG together. 

Later, I'll use this list to assemble ALL of the data, making sure that synonyms are also reflected accordingly.

I think it is impossible to do this "well" otherwise, since we cannot predict if a multi-translation for the same word in English is due to true different senses or rather due to near-synonyms or translation preferences.

**Comment by AnnikaTjuka** [comment]
Sounds good. I am not an expert in any of these languages. But I can go through the mappings before the review to check the obvious cases.
