### ISSUE TITLE
Ranked lists without ranks

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1022]
Ranked lists should have an extra field RANK, but not all lists have this field: https://concepticon.clld.org/contributions/Carling-2019-99

This should be checked systematically.

**Comment by Kristina-Pianykh** [comment]
Do you mean the Culture Labour Intensity (CLI) rank (ranging between H=high, E=equal and L=low?

>  To test the causality of borrowing, we use two different ranks. Firstly, to test need, we use a cultural ranking of concepts by their mobility (of nature items) or their labour intensity and “distance-from-hearth” (of culture items). Secondly, to test prestige, we use a power ranking of languages by their socio-cultural status.

Shall I then expand the abbreviations when adding the ranks?

**Comment by AnnikaTjuka** [comment]
@Kristina-Pianykh Some lists in concepticonlists.tsv do not have a tag for "ranked" in the column TAGS yet. I'll have a look at this.

**Comment by LinguList** [comment]
and the opposite case: a list has **ranked** as tag, but not a column *RANK*.

**Comment by Kristina-Pianykh** [comment]
I've looked through the lists tagged as ranked and there're two lists that would be more appropriate to tag as ratings:
Petroni-2010-100 (S_I column: stability measure)
Vejdemo-2016-167 (the rate of lexical replacement)

Peust-2013-54 is missing a column with stability ranks. Concerning Carlin-2019-99, I was thinking it would be also appropriate to tag it as ratings because the concepts are not ordered in a specific way (from the lowest to the highest) but rather have 3 ranks for each concept: high, equal and low culture labour intensity. My suggestion here would be to add the respective column and change the tag fromranks to ratings.

**Comment by LinguList** [comment]
Yes, basically a good idea. I haven't thought about lists with multiple 
ranks, but think we should not use the existence of multiple ranks as 
the criterion to not label them as ranks, especially since ratings are 
something usually done by humans, where two concepts can have the same 
rating in the end.

In Carling I see only loan and no loan.

What one needs to do in any case is: add an extra column in which the 
rank is expressed as integers that consecutively increase. So one sorts 
by the rank column and then adds a column that assigns the rank. This is 
important, since we decided that this is the way that ranks should be 
expressed. The other values are a "score". A prototypical example is 
Rzymski-2020-XXXX, where the scores are given and also the rank.

**Comment by Kristina-Pianykh** [comment]
I think I understood the idea. I guess I just don’t quite get the difference then between the “ranked” and “ratings” tags if any measure could basically be assigned a rank.

**Comment by Kristina-Pianykh** [comment]
I've just checked Rzymski-2020-1624 and there is no such column as SCORE. I wasn't aware of this convention before. I would then add RANK to ranked/ordered lists in addition to ratings/measurements and I can then rename the column with the latter as SCORE.

**Comment by LinguList** [comment]
Ranks is always an integer rank, starting from one up to the highest 
number in the list.

Score is not a column name, as there are many different scores, so score 
is a category that we identify within norare (concepticon/norare-data).

Scores (usually float, but also integers) in the CLICS list are the 
family_weight, the family_degree and the like.

The rank we add there is derived from one of the scores.

I tend to say that a ranked list is based on a measure that is not 
necessarily showing a Gaussian distribution. Ranks make sense if 
differences are more equally distributed, or if there is a research 
interest in ranking. Borrowability, for example, is rankable, but other 
scores may not be as useful for a rank. Specifically if you have the 
rating scales between 1 and 10 as they use them in psychology, you don't 
have a means to turn that into a rank nicely.

So ranked means: we have a column RANK, that provides an ordering of the 
items that reflects a certain property. Ratings is less strict in 
semantics but should mainly be used for human-based ratings (think of 
the 1 to 10 scale to rate something).

**Comment by Kristina-Pianykh** [comment]
Alright, great, thank you very much for the explanation! I have prepared the changes except that I have a question regarding Joo’s list. When I added it a while ago, I tagged it as ranked although there’re no indications of any particular ranking in the paper. I think I must’ve tagged it as such because of the unusual ordering, which in this case is not alphabetical. The original list is not provided in the source either, the only reference there is to find is the Leipzig-Jakarta list used as the basis and it’s ordered alphabetically. I’m not sure if there was more data to the list because I had taken the concept list directly from the respective lexibank repository. Otherwise it would make sense to remove the tag “ranked”.
