### ISSUE TITLE
New concept DEVIL

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1056]
I thought this issue deserves a separate discussion.

- The word "devil" is already mapped to DEMON in some lists. Should I establish the new concept anyway?

_Originally posted by @AnnikaTjuka in https://github.com/concepticon/concepticon-data/issues/1054#issuecomment-780550755_

We have four lists with the gloss "devil" mapped to DEMON (evil spirit) and three lists unmapped. If we establish a new concept DEVIL it may be best to account for the relation to the Christian belief in the description of the new concept so that the two concepts don't get mixed up.

**Comment by LinguList** [comment]
Yep, that's what I also thought: the whole devil / evil spirit is 
something we should be more clear about, and I'd say in IE languages, 
and wordlists as the one under question, we should link them to DEVIL in 
the Christian sense.

**Comment by chrzyki** [comment]
Thanks @AnnikaTjuka! Changing this would, if I recall correctly, also affect quite a number of Lexibank/CLICS lists, so I'll pay special attention to those.

**Comment by AnnikaTjuka** [comment]
Ok, so we have the following lists mapped/unmapped. I checked off the ones that I'd map to the new concept DEVIL ("Christian evil spirit"). Grierson and Yao include Asian languages, so I wasn't sure whether those should be mapped. If you disagree or think that other lists should be mapped, you can change the checkmarks.
 
Mapped to DEMON

- [ ] Bowern-2012-644-124 (devil [english])
- [X] Buck-1949-1110-1097 (devil [english])
- [ ] Buck-1949-1110-1098 (demon; evil spirit [english])
- [X] Chacon-2019-220-51	(Diabo [portuguese])
- [ ] Grierson-1928-168-45 (Devil [english])
- [ ] Yao-2017-1100-168 (devil [english])

Unmapped

- [X] Hill-2015-999-496 (devil [english])
- [X] Lewis-2016-499-211 (devil [english])
- [X] Zalizniak-2020-2591-635 (devil, satan [english])

**Comment by LinguList** [comment]
This is interesting: Grierson is of course colonialism and Christian, 
but I think they ended up asking for the evil spirit.

For Chacon, I propose to ask @thiagochacon, which mapping would be 
better (obviously, many informants are Christians, but if it is an 
ancient word, etc.).

I think we should also have a look at ideally some anthropological 
literature to see to which degree we find a concept of ONE most evil 
spirit, which could then serve as our base concept, across cultures?

**Comment by Kristina-Pianykh** [comment]
The problem here is that the concept of a demon is present in the Cristian tradition, too. It represents a lower rank in the Christian demonology, i.e. evil spirits, fallen angels, souls of the deceased, etc. (see Buck for an explicit opposition). So I'd say the distinction is to be made not between religious interpretations of these concepts but between the evil as a whole (DEVIL) and quite discrete spiritual entities (DEMON).

The most challenging part is to try to disambiguate the meaning of the related glosses when _devil_ is in fact used generally to elicit a word for _demon_.

I agree with the mappings proposed by @AnnikaTjuka, except I wouldn't map Chacon-2019-220-51 (Diabo [portuguese]). I tried to find some information on spirituality and religion in Arawakan languages (since it's not the focus of Chacon's publication). Very generally, according to [Britannica ](https://www.britannica.com/topic/Taino)and the [Taíno Museum](https://tainomuseum.org/taino/religion/), multiple deities and spirits (in the form of Zemi) are claimed to be especially common in the areas spoken by the Arawak/Taíno. So I'd leave this mapping as it is.

I would also add DiezAlamo-2018-750-750 to the list and map it to DEVIL (the target language is Spanish).

**Comment by thiagochacon** [comment]
"Devil" is in fact a christianization of a native concept that is better translated as "Demon", since it refers to a class of natural beings with zoomorphic and anthropomorphic features, usually associated evil practices, but can also be characterized as a trickster. There is also a class of super-natural beings which can harm people if they have not fully obeyed certain mystical and social rules. These could be glossed as "evil spirits". In the Vaupes area at least, there are different words for these concepts, such as in Tukano wãtĩ 'demon' and wa'i masɨ 'super-natural beings'.

**Comment by Kristina-Pianykh** [comment]
Thank you for providing a little bit more light on the issue, @thiagochacon! It follows then that Chacon-2019-220-51 should not be re-mapped to DEVIL, representing the more abstract (Christian, if you will) notion of the evil.
