### ISSUE TITLE
Emotion circle by Jaeger in four languages

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1127]
In this article, the emotion circle, which is often used for research with experiments, is detailed: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0252408

Their supplement lists not only the experimental results, but also information on the translation in four languages:

https://doi.org/10.1371/journal.pone.0252408.s001

I don't know if we have added this emotion circle already, but think it iwould be useful, even at the cost of adding new concepts.

**Comment by AnnikaTjuka** [comment]
We added the Geneva Emotion Wheel introduced in [Scherer-2013-20](https://concepticon.clld.org/contributions/Scherer-2013-20) and applied in [Jonauskaite-2020-12](https://concepticon.clld.org/contributions/Jonauskaite-2020-12), but haven't added this wheel yet. I'll add the list today so that we get to 404 lists for the upcoming release.
