### ISSUE TITLE
streitberggothic

### ISSUE THREAD

**Issue by martino-vic** [concepticon/concepticon-data#1157]
uploaded a linked conceptlist in [streitberggothic](https://github.com/martino-vic/streitberggothic/blob/master/etc/concepts.tsv), I haven't gone through the manual editing process yet but am also not sure how to do that

**Comment by LinguList** [comment]
This is a specific case, since you have a large concept list of 4000 
glosses. What I'd suggest is to use a slightly different strategy here, 
in making a rather ecclective collection of mapped concepts using pysem 
https://pypi.org/project/pysem, where you only look at proposed mappings 
for the 4000 items. Once done, we can submit this concept list to the 
concepticon, but one can also say that the list is so far too large and 
would involve too much work, which is why we do not submit it to 
concepticon, but have the links in the repository alone.

**Comment by LinguList** [comment]
As to how to use pysem: I could write a small blog post in the next days 
for our CALC blog, that shows you how to use pysem to map concepts. In 
this way, we would make sure that this relatively new procedure is 
accessible to other users.

**Comment by martino-vic** [comment]
Ah, that would sound great! In the meanwhile I could work on the other steps of the cldf-conversion and then get back to the pysem part in the end

**Comment by LinguList** [comment]
Yes, just add a list of the concepts.tsv without links to concepticon to 
the folder etc/. The links are optional, so you can just leave this part 
unlinked!

**Comment by martino-vic** [comment]
What do you mean exactly by "links", just the column "CONCEPTICON_ID" or the entire step 3 "Mapping Concepts to Concepticon" from the blogpost?

**Comment by LinguList** [comment]
If you remove the columns concepticon_id and concepticon_gloss, and 
adjust the code in args.writer.add_concepts, to not add concepticon_id, 
etc., you can run the code without *linking* to concepticon. That's what 
I meant. Sorry if it wasn't clear.

**Comment by martino-vic** [comment]
Ah okay, now I get it, thank you :) No worries, everything still very new to me, but I'm getting there, slowly. Thanks for the patience in any case!
