### ISSUE TITLE
SNAUT resource offers large semantic vectors and lists of most similar concepts

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#116]
http://zipf.ugent.be/snaut/

Could be useful, and they offer their data for download, along with a shell-script that runs comparisons and a nice web-interface that does the same.

**Comment by AnnikaTjuka** [comment]
I'm not sure how feasible it is to add those data sets. The authors provide a list of 200/300 columns for each vector. This seems to be a tedious task because the lists also do not have column names. 

There is another issue with semantic vectors (#493). Should I transfer both to NoRaRe, @LinguList ?

**Comment by LinguList** [comment]
You know, we do not need to add a column name per vector, but would represent vectors in ONE column, separated by a space or comma, similar to tags. So yes, I think they theoretically belong to NoRa**Re** ;)

**Comment by AnnikaTjuka** [comment]
Ah okay, I'll transfer them!
