### ISSUE TITLE
New concept RIFLE

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1234]
_Rifle_ is currently sometimes unmapped, other times mapped as GUN. Maybe we should add another concept RIFLE, as @AnnikaTjuka pointed out in PR #1233.

**Comment by mathildavz** [comment]
We currently have 5 unmapped instances of _rifle_. Is that enough to add a new concept, or should I rather map them to GUN? 
There are also two Chinese glosses translated to _rifle_ that are mapped to GUN at the moment: 

- [ ] Huang-1992-1820-635 | 枪 [chinese]; gun / rifle [english]
- [ ] Yao-2017-1100-831 | 手枪 [chinese]; rifle [english]

@LinguList, your opinion on this would be appreciated.

**Comment by LinguList** [comment]
Yes, sure. The problem is, that the Chinese word is underspecified. QIANG 枪 is a word for gun (Gewehr in German), and 手枪 is handgun, so it is a pistol (you will see that if you google the term). So I'd map the second to PISTOL 3881 and for the first, it is probably fine to map it to gun (but English gun itself is ambiguous).

**Comment by mathildavz** [comment]
Thank you, @LinguList!

**Comment by mathildavz** [comment]
@AnnikaTjuka should I create a new concept for the other instances of _rifle_ or should I simply map them to GUN (or leave them unmapped for now)?

**Comment by AnnikaTjuka** [comment]
@mathildavz I would leave them unmapped for now.
