### ISSUE TITLE
New concept SHINY

### ISSUE THREAD

**Issue by Tarotis** [concepticon/concepticon-data#1244]
There are currently four entries in Concepticon that refer to "shiny", and the Kaufman concept list that I am currently mapping (#170 ) will be the fifth. I'd thus propose to include this new concept. Did I understand correctly that 3 is a threshold that should be reached in order to add a new concept? Or is this already on @mathildavz list anyway?

**Comment by AnnikaTjuka** [comment]
From my side, it's ok to add the concept SHINY. @LinguList What do you think? 
If the decision in this issue is "yes", I'd propose the following workflow:
-  Add the new concept to `concepticon.tsv` 
- Map the available lists that have the concept and are currently in Concepticon.
- Open a PR with these changes.

As soon as the concept is added to the master branch, you can map it in the Kaufman list.

@mathildavz is currently working on other issues (including https://github.com/concepticon/concepticon-data/issues/1173).

**Comment by LinguList** [comment]
Yes. Shiny looks clear enough, but it is also conotated in English. Can we make sure there is no concept covered already, like lustrous if that exists, that vould denote the concept glossed as shiny?

**Comment by Tarotis** [comment]
I just saw that `BRILLIANT` is probably quite close to `SHINY`. Would we say that they denote different concepts? I am not sure. Another possibility is `BRIGHT`, but here I'd argue that they are quite different. Neither "lustrous" nor "glossy" exist.

**Comment by LinguList** [comment]
I suggest to make a new concept and make a clear definition.

**Comment by Tarotis** [comment]
Closed through #1268
