### ISSUE TITLE
Verbs only in imperative

### ISSUE THREAD

**Issue by MuffinLinwist** [concepticon/concepticon-data#1337]
Also discussed in #1333, what should we do in lists where some verbs appear `only in their imperative` forms (not a sign of their infinitive forms on the list)? There are already some lists in Concepticon where they are mapped to their infinitive forms: eat! to EAT, go! to GO, and come! to COME.

Should we leave them unmapped or map them with the `cognate sets` in infinitive?

**Comment by LinguList** [comment]
Typically, imperative is used in some cases where scholars hope that elicitation is more useful than eliciting infinitive or other forms. For example, in Germanic languages, imperative is sometimes a bit more interesting than the infinitive due to sound correpsondences. In these cases, I'd suggest to treat these cases as infinitives, even if that is of course not the true story, but some languages even do not have an infinitive, so there's no way to tell. Imperatives are often unmarked forms, so we'd say: concepticon displays unmarked forms for verbs first, if they are explicitly elicited as imperatives, it may be more appropriate.

**Comment by MuffinLinwist** [comment]
Thank you for the explanation, @LinguList. In the list we have been working on (for [Bora-Muinane](https://glottolog.org/resource/languoid/id/bora1262)) in the PR, there are verbs that appear only in the infinitive form (these are the most), verbs that appear both in their imperative and infinitive forms (namely, `come`, `eat`, `drink`, and `sleep`), and `go!` that appers only in its imperative form. With your clarification, I believe it's safe to assume that the strategy taken on that list is correct:

Map `go!` with [695 GO](https://concepticon.clld.org/parameters/695), but leaving the remaining cases unmapped.

**Comment by MuffinLinwist** [comment]
This strategy has been implemented. Now the list can be found in `concepticon-data/concepticondata/conceptlists/`.
