### ISSUE TITLE
Object Naming Norms for Picture Stimuli (Snodgrass & Vanderwart, 1980)

### ISSUE THREAD

**Issue by alzkuc** [concepticon/concepticon-data#1385]
**Citation:** Snodgrass, J. G., & Vanderwart, M. (1980). A standardized set of 260 pictures: Norms for name agreement, image agreement, familiarity, and visual complexity. Journal of Experimental Psychology: Human Learning and Memory, 6(2), 174–215. [https://doi.org/10.1037/0278-7393.6.2.174]

 **A standardized set of 260 pictures, black and white.** 
  - Pictures accessible via Appendix A, p. 197-204
  - Concepts and Ranks in Appendix B, p. 205-210
  
**PDF accesible via:** https://psycnet.apa.org/doi/10.1037/0278-7393.6.2.174

**Important:** APA does not own the distribution rights to the 260 picture stimuli in Appendix A.

**Comment by LinguList** [comment]
Thanks, I gave you access to also add labels to the issues now. We should start by typing off the data into a spreadsheet. What you can also test, @alzkuc, is to use Transkribus for this task, since preprocessing may be facilitated. If you want to, let me know, so we tell you how to access it.

**Comment by LinguList** [comment]
I suggest to start from page 205, since we have a clear table there. With Transkribus, rating results can also be added. But one should check what they mean there.

**Comment by LinguList** [comment]
The images itself could be annotated with polygons when converting the image to  a scan. But I would probably not do so directly now, until we know if we can every share the images (part can be reused, I guess, but probably not entirely). 

If you check semantic scholar, you see how many people have build on this, it is a huge topic. 

https://www.semanticscholar.org/paper/A-standardized-set-of-260-pictures%3A-norms-for-name-Snodgrass-Vanderwart/144adacded5ed56c35a5f157fe231a0459620ec8

**Comment by LinguList** [comment]
Later extended in : [Cycowicz et al. 1997](https://www.sciencedirect.com/science/article/pii/S0022096596923565?via%3Dihub) and then with French norms by [Alario et al. 1999](https://link.springer.com/article/10.3758/BF03200732).

Quite interesting, since they seem to copy the old lists and then make new lists, similar to the concept lists in historical linguistics. 

They use them also in FMRI studies, but there, people do not often deliver data (see [Spalek et al. 2007](https://www-sciencedirect-com.offsitelib.eva.mpg.de/science/article/pii/S0093934X08000643?via%3Dihub).

**Comment by LinguList** [comment]
@alzkuc, we can close this issue now, as the norms have been added. As a next list, I propose to use the one by Cycowicz et al., since this builds upon Snodgrass and extends it and is then reused by Alario et al. So we have already some areas where there is some overlap to be expected.
