### ISSUE TITLE
Concreteness data

### ISSUE THREAD

**Issue by SimonGreenhill** [concepticon/concepticon-data#321]
Concreteness scores could be useful in the metadata e.g. http://crr.ugent.be/archives/1330

**Comment by xrotwang** [comment]
Bad CC license with ND clause, though.

**Comment by xrotwang** [comment]
Dunno whether extracting a subset of the data already counts as a derivative.

**Comment by LinguList** [comment]
I have the data already and a short script to link automatically, also other types of their data, including frequencies from subtitles, etc. 

I was just hesitating putting this all online now, since, first, I thought one could test things in private (e.g., wordlength, or whatever projects where ratings are needed), and then submit it with the next release.

I also contacted the authors of the study and they told me that they have no problem with putting the values in concepticon, especially, since in their view it's not a derivation.

**Comment by xrotwang** [comment]
I see. Maybe they should re-license on their end? It would still be problematic redistributing the extracted data under CC-BY, wouldn't it?

**Comment by xrotwang** [comment]
Or maybe we can get **them** to contribute an extract of their data to Concepticon - which would even give them a bit more recognition?

**Comment by AnnikaTjuka** [comment]
We've used the supplementary material provided in the Behavior Research Methods [paper](https://link.springer.com/article/10.3758/s13428-013-0403-5#SupplementaryMaterial) and included the data (Brysbaert 2014) in our norm data repository ([#31](https://github.com/lingpy/speech-norms/pull/31)).
