### ISSUE TITLE
Source gloss with (adjectival) modifier in Automatic Concept-Mapping

### ISSUE THREAD

**Issue by laiyunfan** [concepticon/concepticon-data#364]
It does not recognise glosses that partly match the concept, with an additional preceding element. 
For instance, in the Bahing data, the mapped file gave question marks for grass:

> 100	the grass	606	436		???

Actually in the source file, we can find words for "tall grass" and thatch grass:

> 122447	phœrœrœ	tall grass	n df.	BM-Bah	299	Bahing	

> 121735	joːri	thatch-grass	n	BM-Bah	299	Bahing	

Just manually added these items, but one cannot ensure that he finds every instance of them. 
There is a risk that we miss a (partial) cognate.

**Comment by LinguList** [comment]
I agree that this would be a nice feature. We'll have to see how easy it is to implement, as it has been some time since I looked at the code. It would result in an even weaker linking of a concept with a gloss, and if a better linking IS found, it would not show it, according to our hierarchy. Can't promise, however, to be able to implement this any time soon (maybe during the glottobank meeting in Finland, if we finalize concepticon ? let's see).

**Comment by LinguList** [comment]
I suppose we should discuss for enhancing the #382 issue. Either: explicitly deny partial mapping of "grass hopper" to "grass" (my favorite, as this can be dangerous at times) or: allow for a specific similarity level that WOULD include this, but make sure that the similarity level as a default is not allowing for this kind of mapping. Anyway: the #382 issue is crucial to handle this.

**Comment by LinguList** [comment]
Partial mapping should not be supported, in my opiniin now, so the issue can be closed.
