### ISSUE TITLE
Missing concept in our Buck(et) List

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#367]
A student (Iván Andrés-Alba) mentioned this: Concept RIB with Number 4.162 is missing in our list, but it occurs in Buck.

**Comment by Schweikhard** [comment]
Also group (13.192) is missing (it is currently also mentioned in the field of grow)

**Comment by tresoldi** [comment]
We could add both items at the bottom, as `ID`s `Buck-1949-1110-1109` and `Buck-1949-1110-1110`. If someone needs the list in the order of the printed reference, they can sort by the `NUMBER` column.

The alternative (if we can have letters after the number in `ID`) is to change the `ID`s, so that `Buck-1949-1108-163` (bone) becomes `Buck-1949-1110-163a`, with "rib" as `Buck-1949-1110-163b`, and so on.

**Comment by xrotwang** [comment]
I think the first option (add at end) is preferable, because it wouldn't mean retiring otherwise acceptable concept IDs.
