### ISSUE TITLE
Bowern's Data on Hunter-Gatherers

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#42]
This is also interesting in the light of Gram-Bank, they have lots of lexical words, and three lists, one of flora and fauna, one of basic vocabulary, and one of culture vocabulary:
- https://huntergatherer.la.utexas.edu/lexical

At least basic vocabulary should be added.

**Comment by LinguList** [comment]
Update, the first list from the paper has now been added, but it is not clear whether this is the same one they use for the website, so first thing to do here would be to check for the web-links and potentially add them to the concept list.

**Comment by chrzyki** [comment]
So it seems that in total there are three lists used for the database (https://huntergatherer.la.utexas.edu/lexical):

- Flora and fauna vocabulary (342 items)
- Basic vocabulary (207 items) [as opposed to the 204 items in the list previously used for huntergatherer in Lexibank]
- Culture vocabulary (203 items)

Having these properly mapped would make huntergatherer as a dataset much more useful for CLICS. What do you think?

**Comment by CarolinHu** [comment]
I self-assigned this ages ago and would still like to map the list. With regards to the existing Lexibank set, I'm not quite sure how to best proceed in Concepticon... Would appreciate your suggestions, @chrzyki!

- Have three different Bowern lists a,b,c to reflect the 3 categories or make one big list of all categories?

- Use the existing data on Lexibank or the website - there are currently 745 concepts in Lexibank, already including the semantic categories. However, the numbers from the website add up to 752, so there must be something else beside the three missing concepts in the previously used list. (Also, I couldn't find where the IDs in the Lexibank set come from? They exceed number 800 and don't start with 1 either.)

**Comment by chrzyki** [comment]
Well, I personally think that one list works well enough since it'd be the list of *the* database, but of course I'm open to suggestions here.

Regarding website/lexibank: I think my approach would be to take the already-existing data as a starting point but make sure that everything that already is there aligns with the website. If note, I'd assume the website is right (e.g. in the case of the numbers you're mentioning).

Regarding the IDs: The parameter IDs correspond to the sub-page IDs on the website, e.g. `above` has the ID `352` and the data are on this page: https://huntergatherer.la.utexas.edu/lexical/feature/352.
