### ISSUE TITLE
TRADE (898) vs TRADE OR BARTER (2135) (vs BUY (1869))

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#457]
Having 898 and 2135 I think is somewhat problematic. I see a clear difference to 1869, but the definition is rather similar, if not identical.

**Comment by chrzyki** [comment]
@Kristina-Pianykh, would you mind having a look at this and see whether this persists/is an issue at all? Thanks!

**Comment by Kristina-Pianykh** [comment]
@chrzyki I clearly see the difference between the three ([BUY](https://concepticon.clld.org/parameters/1869), [TRADE](https://concepticon.clld.org/parameters/898) and [TRADE OR BARTER](https://concepticon.clld.org/parameters/2135), moreover, there is yet another related concept [BARTER 370](https://concepticon.clld.org/parameters/370):

> BARTER - To exchange goods without involving money.

> TRADE OR BARTER - To exchange goods with or without exchanging money. 

Since there are clearly concepts in some languages, general for both TRADE and BARTER, it still makes perfect sense.

> TRADE - The act or the business of buying and selling for money. Mercantile or commercial business in general or the buying and selling, or exchanging, of commodities, either by wholesale or retail within a country or between countries. 

This one implies a bigger-scale activity of commercial nature (and unlike the two concepts above, this one is not a verb but a noun)

> BUY - To obtain in exchange for money or goods.

Here I would suggest omitting "goods" because this is precisely what makes this concept overlap with BARTER. This will make the difference between BUY and the other related concepts more explicit, also because English dictionaries also point out to the connection of this concept with purchasing, financial transactions and, specifically, money.

**Comment by Kristina-Pianykh** [comment]
Another thing is that  _buy_ in [Zgraggen 1980 380](https://concepticon.clld.org/contributions/Zgraggen-1980-380) is mapped to TRADE OR BARTER while it should probably be remapped to BUY

**Comment by LinguList** [comment]
Okay, so any errors you spot here, @Kristina-Pianykh, modify them and make a PR, this is very useful!

**Comment by Kristina-Pianykh** [comment]
@LinguList shall I also modify the definition of the concept BUY, as has been suggested?
