### ISSUE TITLE
Notes in Dellert2017

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#499]
I noticed that in the concept list Dellert-2017-1016.tsv there is a column named NOTE which includes notes on things that we might want to update on Concepticon, e.g. new concepts we might want to add.

Adding this as an issue in case anyone wants to take these notes as a starting point for further updates.

**Comment by LinguList** [comment]
I'd say we should delete the notes from dellert's list. We have now also the possibility to automatically re-run matches and see what we get. We might want to do that before bigger releases or ones in a while.

**Comment by xrotwang** [comment]
As far as I can tell, keeping these notes wouldn't hurt either. They seem to be generic enough to not be confused with what should go into GitHub issues. So I'd say ignoring rather than deleting will do.

**Comment by LinguList** [comment]
Okay, I was just realizing, that we had before quite a few lists where people would leave things like the similarity score, which don't make sense, as they are just for linking, and I'd like to have this a bit cleaner, so that people are aware that this is published. But yes, the notes here don't hurt.
