### ISSUE TITLE
Collection of concepts that might need some refinement

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#501]
Here is a list of concepts where I think the definition needs to be changed a bit or subconcepts be added but where I wasn't sure about how to proceed (e.g. due to ambiguities). Or should I add separate issues for them?

* meeting house http://concepticon.clld.org/parameters/335
What is a meeting house or a traditional house? One explicitly refers to a religious assembly house, the others are without definition.

* fireplace http://concepticon.clld.org/parameters/185
stove http://concepticon.clld.org/parameters/859
and oven http://concepticon.clld.org/parameters/1143
I think we might want to distinguish between a fireplace (i.e. a fire at the bottom of a chimney in a wall), a hearth (i.e. a place for cooking in the mid of a room), a stove (a fire or other kind of heater where things are put onto to heat them) and an oven (something into which put things to heat them). But I'm a bit at a loss which concept lists to link where, how exactly to write the definitions etc.

* branch http://concepticon.clld.org/parameters/1531
Some refer clearly to both branch and twig, some clearly only to main branch or to twig. Where should I put those that are unclear? "Branch", or "branch or twig"?
I've moved those that clearly refer to "branch or twig" or to "twig" to those new concepts. Clearly to "branch" refer Blust, Borin, Buck and Ogden.

* stab http://concepticon.clld.org/parameters/1434
I moved Key to a new concept "stab to death" (as that's what all the non-english elicitation glosses seem to mean). Anything else we need to move there?

* squeeze http://concepticon.clld.org/parameters/1414
I moved the concepts which mean "wring" or "squeeze or wring" or "fasten or squeeze" to new concepts and the one meaning "fasten" there. The remaining ones might also have a variety of meanings, though, as I was told about the remaining Chinese ones.
Since "squeeze" on Lee2013 means "fasten" as can be seen from the Japanese gloss, should also the entry "squeeze" on Lee2011 be moved to "fasten", or should it remain at "squeeze"?

* boat http://concepticon.clld.org/parameters/1844
Should it refer to any kinds of boats/ships, or only to small ones? Currently it seems to be the former.

* ride http://concepticon.clld.org/parameters/367
Should we remove bicycle from the definition?

* seize http://concepticon.clld.org/parameters/855
grasp http://concepticon.clld.org/parameters/2021
What's the difference?

* all http://concepticon.clld.org/parameters/98
Differentiate between everything, everyone and every in general?

* half http://concepticon.clld.org/parameters/816
Thing or property? Split?

* late http://concepticon.clld.org/parameters/477
and early http://concepticon.clld.org/parameters/672
Differentiate between 
"at the end/beginning of a time period (e.g. the day)" vs. "after/before the expected time"?

* last (endure) http://concepticon.clld.org/parameters/1186
Differentiate between 
"continue to be" vs. "take a certain amount of time"?

* guess http://concepticon.clld.org/parameters/1932
I added a new concept for "guess (successfully)" ('erraten') and moved Key there. The other entries linked to "guess" are clearly about making guesses in general, except for List2014 which is ambiguous. Should it stay there or get a hyperconcept?

* betray https://concepticon.clld.org/parameters/1902
I added a new concept "deceive" but perhaps it needs to be merged with the already existing concept "lie (mislead)".
And on Dellert-2017 there is both "täuschen" ("in die Irre führen") and "betrügen" ("jemanden um Geld"). I have linked both to "deceive".

* abandon https://concepticon.clld.org/parameters/1097
I think the definition is wrong but the concept lists linked have basically no information. Should they be moved to leave? https://concepticon.clld.org/parameters/1752
Depending on the definition we should also move this either to abandon or make a new concept: https://concepticon.clld.org/values/Borin-2015-1532-444

* say https://concepticon.clld.org/parameters/1458
Some might need to be moved to a say/speak-hyperconcept but I'm not sure which ones.

* shout https://concepticon.clld.org/parameters/715
I changed the definition to "To utter in a loud voice." but it's actually not clear whether that's what's meant in all cases.
Some might mean instead "shriek", i.e. "To make a very high, loud sound.", but there is no completely clear case.

* call https://concepticon.clld.org/parameters/1084
some may need to be moved to shout or to call by name

* call by name https://concepticon.clld.org/parameters/180
includes "to utter the name of sb./sth.", "to be named x" and "to be given the name x" - split?

* country https://concepticon.clld.org/parameters/1300
state (politics) https://concepticon.clld.org/parameters/2955
The definitions of state and country might need refinement (I aready rephrased them a bit) - state as hyponym of state?

* master https://concepticon.clld.org/parameters/383
The current definition also includes the meaning "employer" - is that intended?

* chop https://concepticon.clld.org/parameters/155
cut with axe? fell a tree? Both?

* bow https://concepticon.clld.org/parameters/994
Should crossbow get its own concept?

* twist https://concepticon.clld.org/parameters/430
This includes two meanings so I changed the definition to "To wind something around something else or several things around each other." Should it be split into the hyponyms?

* rise (move updwards) https://concepticon.clld.org/parameters/568
all right? or move ambiguous ones to "go up (ascend)"?

* middle https://concepticon.clld.org/parameters/1093
This contains adjectives and nouns.

中間 (List and Sun) means both middle and center but is glossed as "middle". Should it stay at "middle" or be moved to "center or middle"?

当中 means "among" - new concept?

* true https://concepticon.clld.org/parameters/1657
correct (right) https://concepticon.clld.org/parameters/1725
Those seem to mean the same thing, should the be equated?

* knife https://concepticon.clld.org/parameters/1352
Should a new concept be added for small knife? What about khukri knife? (for Kusunda)

* open https://concepticon.clld.org/parameters/1156
This includes several meanings:
"to cause the inside of something (etc. a box or room) to be accessible"
"to 'open' a door or window (i.e. to move it out of the way)" (similar to this might be the only entry on "uncover": https://concepticon.clld.org/parameters/1108)
"to open one's eye" (Sun-1991)
"to remove something lying on top of something else"
"to be open" (Perrin-2010)

* tall https://concepticon.clld.org/parameters/711
high https://concepticon.clld.org/parameters/1265
Also here are several meanings:
"to be in a high spatial position" (this seems to be the meaning of the concept "high")
"to have a great (or greater than average) vertical length" (this seems to be the meaning of the concept "tall")
"to have a great (or greater than average) vertical length (in reference only to humans)"
I would suggest adding that third meaning and a hyperconcept for the first two meanings. But I don't know what to link to which.

* rock https://concepticon.clld.org/parameters/668
stone https://concepticon.clld.org/parameters/857
stone or rock https://concepticon.clld.org/parameters/2125
We might want to equate these concepts. There is only one list that is linked to both rock and stone, and in that case it's not rock but coral rock.

* the spatial ones
up https://concepticon.clld.org/parameters/1591 (upwards?)
above https://concepticon.clld.org/parameters/1741 (position in relation to something else?)
up or above https://concepticon.clld.org/parameters/2379
top https://concepticon.clld.org/parameters/1753 (absolute position?)
(related perhaps peak and summit)

down https://concepticon.clld.org/parameters/1326 (downwards?)
below or under https://concepticon.clld.org/parameters/1485 (position?)
down or below https://concepticon.clld.org/parameters/2094 (hyperconcept for the other two?)
For this there already is an issue open: https://github.com/clld/concepticon-data/issues/44242

**Comment by LinguList** [comment]
> meeting house http://concepticon.clld.org/parameters/335
What is a meeting house or a traditional house? One explicitly refers to a religious assembly house, the others are without definition.

they are the same concept lists (derived from each other), so they should link to the same entry. So split off the traditional house and leave the meeting house. Traditional house can be left unlinked.

> rock https://concepticon.clld.org/parameters/668
stone https://concepticon.clld.org/parameters/857
stone or rock https://concepticon.clld.org/parameters/2125
We might want to equate these concepts. There is only one list that is linked to both rock and stone, and in that case it's not rock but coral rock.

Don't understand the point. Refinement internally is okay, but leave them three separate. 

Ignore spatial concepts for the time being. Some languages nominalize them only (Chinese), so it is difficult to settle this consistently without knowledge in particular glossing languages, etc., or target languages, so let's not have this discussion now.

Tall and high is also too much for now, let's please leave it as is and see what happens later.

For "open", Sun is mislinked, as I remember that I added a concept "open one's eye", if not, we have to check with the Chinese concept!

> I moved Key to a new concept "stab to death" (as that's what all the non-english elicitation glosses seem to mean). Anything else we need to move there?

Check all lists derived from key! WOLD (=Haspelmath and Tadmor), etc. Also List-2014.

> Should a new concept be added for small knife? What about khukri knife? (for Kusunda)

leave it unlinked

> true https://concepticon.clld.org/parameters/1657
correct (right) https://concepticon.clld.org/parameters/1725
Those seem to mean the same thing, should the be equated?

I am not sure about this. If one list distinguishes the two, it cannot be merged.

> 中間 (List and Sun) means both middle and center but is glossed as "middle". Should it stay at "middle" or be moved to "center or middle"?

Middle is fine.

> 当中 means "among" - new concept?

Leave unlinked.

> This includes two meanings so I changed the definition to "To wind something around something else or several things around each other." Should it be split into the hyponyms?

possible

> chop https://concepticon.clld.org/parameters/155
cut with axe? fell a tree? Both?

it's fine for me as is. They mean the same thing: to cut with an axe. No need for now to change much.

> rise (move updwards) https://concepticon.clld.org/parameters/568
all right? or move ambiguous ones to "go up (ascend)"?

Chinese concepts all mean "ascend of heavenly bodies", don't we have this already somewhere else?

> call by name https://concepticon.clld.org/parameters/180
includes "to utter the name of sb./sth.", "to be named x" and "to be given the name x" - split?

I'd leave it for now, maybe make a separate issue, and handle it in one PR later, if you feel it's worth the pain.

> middle https://concepticon.clld.org/parameters/1093
This contains adjectives and nouns.

There's only Ringe being potentially inconsistent. Unlinking this will do the trick.

> country https://concepticon.clld.org/parameters/1300
state (politics) https://concepticon.clld.org/parameters/2955
The definitions of state and country might need refinement (I aready rephrased them a bit) - state as hyponym of state?

redefining is fine, as it doesn't touch the links.

> I changed the definition to "To utter in a loud voice." but it's actually not clear whether that's what's meant in all cases.
Some might mean instead "shriek", i.e. "To make a very high, loud sound.", but there is no completely clear case.

I don't see a problem, once the definition is changed. Most are linked properly.

> call https://concepticon.clld.org/parameters/1084
some may need to be moved to shout or to call by name

yes, maybe also leaving this unlinked, but basically: put it in a separate issue, we may need more discussion and reflection.

> bow https://concepticon.clld.org/parameters/994
Should crossbow get its own concept?

Yes. Or leave it unlinked.

SAY: is fine for me, no need to move anything from quickly eyeballing.

> Should we remove bicycle from the definition?

yes

> I think we might want to distinguish between a fireplace (i.e. a fire at the bottom of a chimney in a wall), a hearth (i.e. a place for cooking in the mid of a room), a stove (a fire or other kind of heater where things are put onto to heat them) and an oven (something into which put things to heat them). But I'm a bit at a loss which concept lists to link where, how exactly to write the definitions etc.

As a new rule: make a separate issue but don't change for now. We can discuss, and maybe more people share their opinions.

> Some refer clearly to both branch and twig, some clearly only to main branch or to twig. Where should I put those that are unclear? "Branch", or "branch or twig"?
I've moved those that clearly refer to "branch or twig" or to "twig" to those new concepts. Clearly to "branch" refer Blust, Borin, Buck and Ogden.

I think it's okay as is. Not many languages make a real difference between twig and branch. And there's no concept lists that separately lists thte two, right?

> Since "squeeze" on Lee2013 means "fasten" as can be seen from the Japanese gloss, should also the entry "squeeze" on Lee2011 be moved to "fasten", or should it remain at "squeeze"?

Lee was trying to translate the Swadesh list, so he had an idea of "squeeze". So leave it linked where it is in this case, we don't have the expertise to judge how well he translated the Japanese concept.

> Should it refer to any kinds of boats/ships, or only to small ones? Currently it seems to be the former.

the former, if this is the current mapping.

> seize etc.

Yes, merge the two, I agree. 

> half

leave as is, only two lists may have more interpretations, but Chinese has both meanings.

> Differentiate between
"at the end/beginning of a time period (e.g. the day)" vs. "after/before the expected time"?

Makes sense, if you can distinguish this in the lists. But I'd opt for a hyperconcept in addition.

> last / endure

I think all lists mean "dauern", and if they no further specify, it's not many lists, maximally an issue, but no further splitting for the time being.

> I added a new concept for "guess (successfully)" ('erraten') and moved Key there. The other entries linked to "guess" are clearly about making guesses in general, except for List2014 which is ambiguous. Should it stay there or get a hyperconcept?

Be generally careful about moving KEY as it is the basis of WOLD and List, so the same underlying questionnaire was used. I'd prefer to have those together rather than making too finegrained distinctions.

> I added a new concept "deceive" but perhaps it needs to be merged with the already existing concept "lie (mislead)".
And on Dellert-2017 there is both "täuschen" ("in die Irre führen") and "betrügen" ("jemanden um Geld"). I have linked both to "deceive".

I'd unlink the first one in Dellert and link the second one to "betray" (?). Lie (mislead) is "lügen", that is, to speak untrue things.

> abandon

please just leave it. If lists are unspecific, at least the gloss is mostly the same among them.

Many points, difficult to keep all in track. Please make a PR with what you have (but be careful with things I mentioned above), and put questionable things to separate issues, so we can just keep them and reflect further and tackle them in steps, okay? In many cases, you bring up good points, but in some cases, I'd not rush to solve them, as they are inherently problematic, so that we may wait until we find lists that specify further to get a better understanding. The rule is: we NEED different concept if one list specifies two different ones, and we always avoid to have too many mergers inside the same lists (arther leave one concept unlinked).

**Comment by Schweikhard** [comment]
> Don't understand the point. Refinement internally is okay, but leave them three separate.

Stone and rock can be used synonymous, and we don't know which meaning each list refers to.

> For "open", Sun is mislinked, as I remember that I added a concept "open one's eye", if not, we have to check with the Chinese concept!

I find CLOSE (EYES) but none for "open one's eye". I'll add a new concept for it, and also for "open" as an adjective in Perrin.

> Chinese concepts all mean "ascend of heavenly bodies", don't we have this already somewhere else?

I don't see any other concept of this meaning. Okay, then I'll move those to GO UP (ASCEND) that clearly do not refer to heavenly bodies. For the two lists by Marrison and the one by Bowern, we have no info which meaning it is. Could even include RISE (ONESELF), so I'll move them to GO UP OR RISE (ONESELF). Seems more likely to me that they refer to rise in general than only to heavenly bodies.

> There's only Ringe being potentially inconsistent. Unlinking this will do the trick.

Borin, Dellert and Haspelmath have "the middle", Ringe and Buck have "middle (adj.)" and the rest is ambiguous as far as I see.

> I think it's okay as is. Not many languages make a real difference between twig and branch. And there's no concept lists that separately lists thte two, right?

There is (Dellert). That's why I added a new concept (plus a hyperconcept).

> Lee was trying to translate the Swadesh list, so he had an idea of "squeeze". So leave it linked where it is in this case, we don't have the expertise to judge how well he translated the Japanese concept.

Sophie asked her sister, who is a Japanese translator, and she confirmed that it means "tighten" as in "to tighten a belt or seat belt".

> I'd unlink the first one in Dellert and link the second one to "betray" (?). Lie (mislead) is "lügen", that is, to speak untrue things.

The first one was unlinked but might kinda fit DECEIVE. I linked the second one to DECEIVE because BETRAY has a different definition.

I've now made the changes mentioned here and on the pull request and will open issues for the remaining ones.
I'll push the changes on Monday - concepticon test doesn't seem to work here on Windows/Cygwin.

**Comment by LinguList** [comment]
1. add twig for dellert is okay, but all other lists should be linked to "branch". If you don't add a hyperconcept, we can't compare them otherwise.

2. Please link all linkings of Lee back. You did only read the Japanese glosses, not the content of the wordlist, and not the paper, or did you? We have Lee's email, you could write him and ask him directly, but since he bases his study on data by Shiro, whom we have also linked, please check this list too, it's about the history of how these lists evolved as well. Similar with "pelt". It may well be that Shiro was the one who mistranslated things from English, but this means, Shiro should also be checked again.

**Comment by Schweikhard** [comment]
1. I have already added the hyperconcept BRANCH OR TWIG.

2. Okay. Lee is only fur/pelt and squeeze/fasten, no other changes, so that will be easy to undo.

**Comment by AnnikaTjuka** [comment]
@Schweikhard Is this issue resolved?

**Comment by Schweikhard** [comment]
No. Some parts are, some aren't. Would it be better to open new individual issues for those which aren't resolved yet and may need further discussion?

**Comment by AnnikaTjuka** [comment]
That's a good solution to get a better overview of the unresolved issues.

**Comment by AnnikaTjuka** [comment]
@LinguList I went through the whole discussion and most of it is already resolved or was discussed in other issues. I opened one issue for an unresolved suggestion. Can I close the issue?

**Comment by AnnikaTjuka** [comment]
I'll close this issue now. Concrete suggestions were implemented and unresolved discussions were added to new issues.
