### ISSUE TITLE
UNTRUTH 475 and LIE (FALSEHOOD) 2826

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#709]
Again, the two concept sets seem very similar to each other, if not identical, judging by their definitions and glosses, mapped to them.

**Comment by LinguList** [comment]
Okay, this is a good example for a misunderstanding in different terms for same concepts. Since people expect "LIE (FALSEHOOD)" when they see "lie (noun)", they may not map to "untruth". 
We can list UNTRUTH as alias of LIE (FALSEHOOD) by adding the ID 2826 in the last cell of concepticon.tsv in the line for UNTRUTH. Then one needs to remap to LIE (FALSEHOOD) of all other concepts. I think the LIE should be in th egloss, so taking 2826 instead of 475 as basis seems more useful to me.
