### ISSUE TITLE
Closing resolved issues

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#716]
I propose to close the following issues:

- [x] #50 
- [ ] #111 
- [x] #301 
- [x] #428 
- [ ] #436 
- [ ] #476 
- [ ] #580 
- [x] #618 
- [x] #681 
- [x] #679 

Some of them seem to be resolved by PR or I found a corresponding dataset in the conceptlists.tsv.

Note that I only skimmed them, so they might not be fully resolved. Please have a look at them and close them if appropriate.

**Comment by chrzyki** [comment]
Thanks @AnnikaTjuka. Closed a couple where I was sure, left some for the others to check.

**Comment by AnnikaTjuka** [comment]
Found some others:
#367 @Schweikhard or @tresoldi is this issue resolved?
#708 #680 @Kristina-Pianykh I think these are resolved with your latest PR :)

**Comment by tresoldi** [comment]
@AnnikaTjuka it is not: https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Buck-1949-1108.tsv

I think the discussion halted because we could add the missing concepts at the end of the list (as in my first suggestion, that @xrotwang accepted), but it would also mean changing the `1108` to `1110`.

**Comment by AnnikaTjuka** [comment]
Thanks everyone for closing some of the issues (6 out of 10 :+1: )! I'll close this issue now because the other issues weren't yet solved. Maybe we should consider a "clean-up" sprint at some point, where we concentrate on solving the open issues.
