### ISSUE TITLE
How to handle automatically mapped metadata in concepticon?

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#719]
@xrotwang and @chrzyki, based on #717, an important question here: if we follow my suggestion of linking some metadata sets regularly, upon new releases, automatically, how do you think it will be best to proceed? See the blogpost here, where I give s short code (that could be integrated to pyconcepticon, and also enhanced): https://calc.hypotheses.org/2250

If we decide to do mappings automatically upon each release, we should have an extra folder with the original data to check against them, right? And in some cases, such as wikipedia, for example, it may be better to crawl data, as we can't use a dump.

This may also hold for babelphy and wordnet.

But since this would blow the repository size, I was thinking if it might not be better to open a new repository to handle the cases there? Maybe even in a way that we always download the most recent versions, in case they are available?

Any ideas are, in any case, very welcome.

**Comment by xrotwang** [comment]
I'm not sure we'd have to keep the raw data from other sources in our repository - for some sources this may even be problematic because of licensing. For Glottolog, I just have [the code](https://github.com/glottolog/pyglottolog/tree/master/src/pyglottolog/links) that is run before a release to update the links.
But of course this code could also make use of data in separate repositories - possibly even private ones - which keep the raw data. Again, we have such cases for Glottolog, too - where a publishers catalog is kept in a private repository, and a Glottolog refprovider is created from it periodically.

**Comment by LinguList** [comment]
Excellent. We could for now just use our norm data repository to create all metadatasets, based on code we have in the sources, but which we cannot share. And in that very repository, which we'll leave closed, we can also try some code that actively downloads the data in case of new updates. And once we feel confident, we can add the python code (for wikipedia, for example).
