### ISSUE TITLE
HE-GOAT, MALE GOAT and FEMALE GOAT

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#730]
In the presence of two duplicate concepts HE-GOAT and MALE GOAT, all the relevant glosses are mapped to the former while it is not listed as a replacement of the latter.

If we add the replacement ID of MALE GOAT to HE-GOAT, I suggest renaming FEMALE GOAT to SHE-GOAT for the sake of consistency in naming. There's just one gloss mapped to FEMALE GOAT so I assume renaming wouldn't be of a drastic impact.

**Comment by AnnikaTjuka** [comment]
This schema could also be applied to boar or rather pig in general, see also #466.

**Comment by LinguList** [comment]
Yes, we need consistency, but MALE vs. FEMALE are more flexible terms. So I suggest to test first to indicate HE-GOAT as an alias for MALE GOAT, so we can leave the other cases.

I also suggest to apply some query into meta-data and add information on male-female counterparts for animals and kinship terms. @Schweikhard may have a good idea how to name these, given that you have been working on the concept relations. I'd like to have this stored as information that SOW (FEMALE PIG) is the counterpart of BOAR (MALE PIG) [as a new concept]. 

Any ideas on a good name for a relation here? Maybe just "opposite_sex"?

And the rule for naming is: if there is a term, like "stallion" for male horse, we use that term and put the specification with "male/female" in brackets.

**Comment by Schweikhard** [comment]
The relation name "opposite_sex" seems good - we would need consistency which sex we put into which column, though, as this is a non-directional relation and all other relations we have are directional, with the exception of antonymof.

Also, thus far all relation names just consist of a single alphabetic string, so that would then be "oppositesex", without underscore.

We basically always have a concept for the species in general as well, so the other solution would be to have "female" and "male" as relations from the general species to the female and male concepts, respectively.

**Comment by LinguList** [comment]
Yes, female and male is okay. Or female_of and male_of, as this would
also work for German "Katze" male_of "Kater", right?

**Comment by LinguList** [comment]
BUT, this would mean: male_of is only in one direction, male_of is not
the opposite of female_of, only in cases like katze and Kater, etc. but
not in "cattle" male_of bull, and "cattle" female of cow

**Comment by Schweikhard** [comment]
> only in cases like katze and Kater, etc. 

And we would likely not have such an ambiguous concept as Katze ("cat in general or female cat") anyway.

> but not in "cattle" male_of bull, and "cattle" female of cow

Yes it would be basically a kind of hyponymy.
