### ISSUE TITLE
Concepticon 2.3.0 release preparations

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#743]
Release deadline: March 2nd, Monday, please check [milestones](https://github.com/concepticon/concepticon-data/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.3)!

General TODOs:

- [x] add contributors from previous versions, update `CONTRIBUTORS.md`
- [x] add @AnnikaTjuka and @MacyL as editors
- [x] recreate stats & links
- [x] release on Zenodo
- [x] update CLLD app
- [ ] make release news announcement

Issues:

- linking problems: ~~#737~~, ~~#738~~, ~~#739~~, ~~#740~~
- definition updates, re-linking: ~~#733~~, ~~#730~~, ~~#726~~, ~~#722~~, ~~#700~~
- ~~check relations: #631 (@Schweikhard, is this done?)~~

Documentation:

- ~~updated [CONTRIBUTING.md](https://github.com/concepticon/concepticon-data/blob/master/CONTRIBUTING.md), see #612 and @AnnikaTjuka's tutorial~~

Lists:

- [x] 310 lists, done!

**Comment by chrzyki** [comment]
Updated, please check the [2.3 milestone](https://github.com/concepticon/concepticon-data/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.3) for more lists.

**Comment by AnnikaTjuka** [comment]
We could solve one more issue: #554 for the 2.3 milestone.
If I understand the discussion correct we only need to extend the definition of COUNT. My proposition:

"To enumerate the digits of one's numeral system or determine the amount of something."

**Comment by CarolinHu** [comment]
Funny, I was having a look at the very same thing just now. I think it already has been solved and the issue can be closed, 1420 COUNT is "To determine the amount of something or to enumerate the digits of one's numeral system" in concepticon.tsv. Or is there perhaps anything that still should be done about this issue, @Schweikhard?

**Comment by chrzyki** [comment]
Seems this was done/modified here: https://github.com/concepticon/concepticon-data/commit/3c73bdf687c14499254b83292f25d5abd644e076.

**Comment by Schweikhard** [comment]
Yes, That one can be closed.

**Comment by CarolinHu** [comment]
Thank you. Those are the issues that are still marked as 2.3 milestone:

#151, #251, #391, #427, #490, #677, #732, #750
= all of them new concept lists that can be moved to the next milestone, presumably

#396, #593 
= not concept lists, but other issues that will be relevant for future releases

Finally, there are some issues left that could still be solved before the release (?) :

#367 - as far as I can see, a solution was already agreed upon, it just needs to be implemented. I could do this, it seems pretty straightforward.
#402 - renaming the concepts so that SAME-SEX is in brackets can be done easily but since Vanikin/Parabank (#391 ) is not added yet, this issue might just be postponed to the next milestone?
#436 - I am not sure whether something is still missing from the proposed concepts or whether this was just kept open as reference.
#579

**Comment by AnnikaTjuka** [comment]
Thanks @CarolinHu ! I had a similar attempt for closing issues (#716 ) in which I also listed some of the issues, you mentioned as "could be solved". So I'd suggest that we resolve the rest of the issues after the release.

**Comment by Schweikhard** [comment]
Closed Buck and moved Zgraggen to upcoming, so all milestone issues solved!

**Comment by AnnikaTjuka** [comment]
I did a little counting and since the announcement of the 2.3 release we closed **40(!)** issues. Well done everyone!

**Comment by chrzyki** [comment]
Done

* https://zenodo.org/record/3706687
* https://github.com/concepticon/concepticon-data/releases/tag/v2.3.0
* https://concepticon.clld.org

Only needs announcements as you see fit @LinguList.

**Comment by SimonGreenhill** [comment]
Well done @AnnikaTjuka for shepherding this through! Thanks everyone!
