### ISSUE TITLE
GRUEL (1167), MUSH (3651), CONGEE (2049) and porridge?

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#746]
We have three narrower/specific concepts for food derived from porridge:

- GRUEL (which is a thinner version of porridge, often with some kind of fine grains e.g. flour)
- MUSH (starchier porridge, particularly with cornmeal)
- CONGEE (rice porridge version)

The linked concepts don't necessarily reflect the finer distinctions and a general porridge concept might be justified?

Also I think https://concepticon.clld.org/values/Sun-1991-1004-396 incorrectly links to GRUEL and instead should link to CONGEE (@MacyL please confirm).

**Comment by AnnikaTjuka** [comment]
I think I found another mismapping:
Wang-2004-471-285	稀（粥） [chinese]; watery/thin (porridge) [english] is mapped to 207 SPARSE.

**Comment by AnnikaTjuka** [comment]
About introducing a new concept: I would be in favor of introducing the general concept. If I remember correctly, "porridge" was listed in one or two norm data sets.

**Comment by MacyL** [comment]
checking with 白漢辭典, the author meant watery or clear, Chinese is 清 （Chen's data map to PURE, but PURE is 純) or 稀 (WATERY), and "congee" is an example. 
the word in the lexical data is "tɕʰiaŋ⁵⁵" (Wang's data). In the dictionary, congee is "qiainl pail vrt" (reflexes, it's not real IPA). Overall, it's not CONGEE, but I am not certain if SPARSE is the right mapping, either. Because "qiainl" could be watery like "clear soup", "qiainl" can also describe 清風 (clear wind)
So I would recommend to unlink this one or re-map to WATERY.

> I think I found another mismapping:
> Wang-2004-471-285 稀（粥） [chinese]; watery/thin (porridge) [english] is mapped to 207 SPARSE.

**Comment by MacyL** [comment]
I guess this issue can be closed?

**Comment by chrzyki** [comment]
Yes, thanks for helping with this.
