### ISSUE TITLE
Rice (husked, pounded)

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#764]
I would propose some new concepts for rice. Currently we have RICE (the seeds), in COOKED, UNCOOKED and UNHUSKED and some other forms, and RICE PLANT, and I'm about to add RICE SEEDLING.
But RICE also includes husked rice and pounded rice, and one case that includes both the plant and the husked rice.
Could someone more in the know about these matters tell me whether husked and pounded rice should get different concepts or share one?

**Comment by Schweikhard** [comment]
Oh, and @MacyL could you take a look at https://concepticon.clld.org/parameters/3050
and tell me which of those are rice seedlings in particular?

**Comment by MacyL** [comment]
Short answer: 
1. Castro-2010-511-75  Uncertain 
2. Castro-2015-608-66 SEEDLING
3. Chen-2012-888-223 SEEDLING
4. Huang-1992-1820-406 SEEDLING
5. Sun-1991-1004-221 SEEDLING
6. Wang-2004-471-137 SEEDLING

Long answer:

1. Castro-2010-511 I can only find the English version of the book. Judging by my understanding of Castro's data, he often provide a wordlist with Chinese gloss. Considering there might be differences from time to time in the English gloss and Chinese translation (or the other way round), I am not certain with this concept whether this is SEEDLING or RICE SEEDLING. 

2. Castro-2015-608, check with 水語拼音介紹，it is "seedling" ( /ʔdja³/, Zhonghe variety). The rice seedling is oux qdyac (not IPA) in 水語拼音介紹.

3. Chen-2012-888 the equivalent of Chinese 苗 (checked the mienic dialects). 

4. Huang-1992-1820,  I checked the Gyalrong (Dr. Lai's help) and Bai language (白漢辭典). However, it can also be RICE SEEDLING according to the book's quotation mark usage. Since it's the most important crop in Asia, people often imply the seedling as rice seedling. For concepticon, I would suggest it to map to a more general term.

5. Sun-1991-1004. I checked the Bai language.

6. Wang-2004-471. it's /dʐi21/.

**Comment by Schweikhard** [comment]
Thanks! Then I'll leave it as SEEDLING for now (there are two other lists that clearly specify rice seedling, so the new concept will be there for those).

**Comment by MacyL** [comment]
cool, I will find time to check the data in Castro-2010-511

> Thanks! Then I'll leave it as SEEDLING for now (there are two other lists that clearly specify rice seedling, so the new concept will be there for those).

**Comment by Kristina-Pianykh** [comment]
Regarding the difference between husked rice and pounded rice:
Google search returns mostly 'hand-pounded rice' referring to the specific method of removing the outer layer from rice seeds. The description below provides even more details:

> Hand pound Rice (kai kuthal arisi in Tamil), on the other hand is a rice whose husk has been removed by using a stone grinder or a stone apparatus similar to a mortar and pestle.
http://chefinyou.com/faq/difference-between-hand-pound-rice-brown-rice

Husked rice, on the other hand, refers not to the method of removing husk but the result itself. So in the end, husked and hand-pounded rice is the same thing but the former focuses on the result while the latter - on the method.

**Comment by Schweikhard** [comment]
Thanks!
The difference seems to be pounded rice still includes the brown bran, whereas if it's husked by modern methods, that is removed, too. But as it's not a given that our "husked rice" is made with modern methods or by pounding, I guess it's safest to map all of them to some HUSKED RICE.

**Comment by chrzyki** [comment]
What's the status on this?

**Comment by LinguList** [comment]
yes, @macyl, @Schweikhard, do we have this solved?

**Comment by Schweikhard** [comment]
Well the husked or pounded rice is still treated like any edible RICE, yet I guess that's not necessarily an issue as edible rice is usually husked or pounded. So I guess this could be considered solved.
