### ISSUE TITLE
Johansson-2020-344: Measuring sound symbolic concepts in the Swadesh list

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#786]
* https://doi.org/10.1515/lingty-2020-2034

Not sure if data and code are submitted.

**Comment by LinguList** [comment]
Date here: https://osf.io/3dsn6/

**Comment by XachaB** [comment]
I have a (local) branch with changes to Johansson-2020-344, following what @LinguList  described in lexibank/johanssonsoundsymbolic/pull/1: 

> we do not rename concepts in etc, instead, the concept list in conceepticon should be adjusted, in this case then, with a colummn "concept_in_source"

and

> You can make a PR to Concepticon, for this, no rights are needed.

However, it seems that I can not push my branch in order to make a PR, and that I do need specific rights. Could someone give me rights to push to this repository ? @AnnikaTjuka, are you the right person to whom to ask this ?

**Comment by LinguList** [comment]
You can also just fork the whole repository to your github, edit, and 
then propose a PR, I think that should work without any rights, right?

**Comment by XachaB** [comment]
Annika gave me rights, and I have made a PR here: concepticon/concepticon-data/pull/1005
I didn't know one could make a PR from a fork, thanks for the suggestion, it will be useful :+1:
