### ISSUE TITLE
calm (of sea) in Key and other lists is wrongly linked.

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#970]
We treat this as an adjective, but it seems, this is also a noun, so it is "the calm", that is, die Meeresstille.

**Comment by Schweikhard** [comment]
I would understand "calm (of sea)" as an adjective, just the translations in Key are unreliable because it's ambiguous, and at least 2 of them are to unambiguous adjectives.

In Haspelmath-2009, which it's based on, it's explicitly an adjective, as in several other lists. I don't see any that would clearly refer to the noun.

What should be corrected is Perrin-2010-110-10 CALM [english]; calme [french]; ruhig [german] and Bulakh-2013-870-854 calm [english] as this likely rather is QUIET or SILENCE if anything.

**Comment by LinguList** [comment]
Well, please check the translations then. They have both nouns and
adjectives in Portugues and Spanish:
https://concepticon.clld.org/contributions/Key-2016-1310, and they all
refer to the sea, Russian has an adjective, but it is similar to other
cases, where it is not clear if a noun or adjective reading is intended,
so one should split it up then, or UNLINK it.

**Comment by Schweikhard** [comment]
I think the current mapping was based on the policy of mapping Key always to the same thing as Haspelmath as it's based on that and as the latter has example sentences for disambiguation.

But I agree it's better to rather go by what the translations say, as that is the actual data, and therefore a splitting into the languages would be in order, possibly even with splitting entries that have more than one value into separate lines.

As that would be a major task, for now, unmapping is probably the best solution.

**Comment by LinguList** [comment]
Yes, unmapping this is then our strategy. With my new blogpost at
https://calc.hypotheses.org, I also found some new concepts that can be
added, when linking my German version of IDS. I'll do that at some
point, and then also tackle this issue. By unmapping, we also do a
service in so far as we prevent that problematic colexifications from
IDS swap into CLICS ;)

**Comment by LinguList** [comment]
With the List-list being mapped, we can also unmap this in the IDS list before releasing 2.4 #976

**Comment by chrzyki** [comment]
What exactly would be the fixes here? Particularly with the new `3820 CALM (OF SEA)` in mind?

**Comment by Schweikhard** [comment]
By the current definitions, that new concept is a duplicate to the existing CALM, both describing the property of a calm sea. I would suggest changing CALM (OF SEA) to refer to _the_ calm instead, which is also what List-2020-1365-19 (for which the concept was created) describes.

As mentioned above, the following could be unmapped due to being ambiguous:
 Perrin-2010-110-10, Bulakh-2013-870-854, Key-2016-1310.

**Comment by chrzyki** [comment]
> By the current definitions, that new concept is a duplicate to the existing CALM, both describing the property of a calm sea. I would suggest changing CALM (OF SEA) to refer to _the_ calm instead, which is also what List-2020-1365-19 (for which the concept was created) describes.
> 
> As mentioned above, the following could be unmapped due to being ambiguous:
> Perrin-2010-110-10, Bulakh-2013-870-854, Key-2016-1310.

Could you please prepare a quick PR for this?

**Comment by Schweikhard** [comment]
about to.

**Comment by chrzyki** [comment]
Thank you! :)
