### ISSUE TITLE
The 1908 Okanagan word lists of James Teit (1908)

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#997]
https://scholarworks.umt.edu/cgi/viewcontent.cgi?article=9308&context=etd

**Comment by Kristina-Pianykh** [comment]
I'm currently working on this list (I hope @chrzyki doesn't mind that I'm taking away his issue, otherwise I'll pick something else) and have difficulty structuring it properly concepticonwise. Here're a couple of examples to show what I mean:
| ID        | NUMBER           | ENGLISH  |
| ------------- |:-------------:| -----:|
| Teit-1908-635-43 | 43    |  grandchild |
| Teit-1908-635-43a? | 43a   |  child of daughter |
| Teit-1908-635-43b? | 43b   |  child of son |
|...|...|...|
| Teit-1908-635-46 | 46    |  step father|
| Teit-1908-635-46a? | 46a   |  real father not dead |
| Teit-1908-635-46b? | 46b   |  real father dead |

There are overall 635 numbered items but due to a considerable number of "extended" concepts, the list overall contains 697 entries. I'm confused about how I should assign them IDs (Teit-1908-635-1, Teit-1908-635-1a, etc.) and what the concepticon policy here is. I would appreciate any pointers here.

Here's a screenshot of how it looks like in the source:
![2021-04-24_17-09-07](https://user-images.githubusercontent.com/51445294/115963519-f0f3a280-a51f-11eb-8035-69f4a44b52a2.png)
:

**Comment by chrzyki** [comment]
My vote is for keeping it simple:

| ID | Concept |
| -- | ---------- |
| Teit-1908-635-43 | grandchild
| Teit-1908-635-44 | grandchild (child of daughter)
| Teit-1908-635-45 | grandchild (child of son)

**Comment by Kristina-Pianykh** [comment]
Then it would make sense to make two columns: for the original numbering (1 through 635) and the concepticon numbering (1 through 697-ish).

**Comment by chrzyki** [comment]
Yep, that's a good idea, also potentially for Lexibank mappings etc.
